export type CityData = {
  city: string
  country: string
  timezone: string
  utcOffset: string
}

// Top 100 cities by population with timezone data
export const CITIES: CityData[] = [
  { city: 'Tokyo', country: 'Japan', timezone: 'Asia/Tokyo', utcOffset: 'UTC+09:00' },
  { city: 'Delhi', country: 'India', timezone: 'Asia/Kolkata', utcOffset: 'UTC+05:30' },
  { city: 'Shanghai', country: 'China', timezone: 'Asia/Shanghai', utcOffset: 'UTC+08:00' },
  { city: 'Sao Paulo', country: 'Brazil', timezone: 'America/Sao_Paulo', utcOffset: 'UTC-03:00' },
  { city: 'Mexico City', country: 'Mexico', timezone: 'America/Mexico_City', utcOffset: 'UTC-06:00' },
  { city: 'Cairo', country: 'Egypt', timezone: 'Africa/Cairo', utcOffset: 'UTC+02:00' },
  { city: 'Mumbai', country: 'India', timezone: 'Asia/Kolkata', utcOffset: 'UTC+05:30' },
  { city: 'Beijing', country: 'China', timezone: 'Asia/Shanghai', utcOffset: 'UTC+08:00' },
  { city: 'Dhaka', country: 'Bangladesh', timezone: 'Asia/Dhaka', utcOffset: 'UTC+06:00' },
  { city: 'Osaka', country: 'Japan', timezone: 'Asia/Tokyo', utcOffset: 'UTC+09:00' },
  { city: 'New York', country: 'United States', timezone: 'America/New_York', utcOffset: 'UTC-05:00' },
  { city: 'Karachi', country: 'Pakistan', timezone: 'Asia/Karachi', utcOffset: 'UTC+05:00' },
  { city: 'Buenos Aires', country: 'Argentina', timezone: 'America/Argentina/Buenos_Aires', utcOffset: 'UTC-03:00' },
  { city: 'Chongqing', country: 'China', timezone: 'Asia/Shanghai', utcOffset: 'UTC+08:00' },
  { city: 'Istanbul', country: 'Turkey', timezone: 'Europe/Istanbul', utcOffset: 'UTC+03:00' },
  { city: 'Kolkata', country: 'India', timezone: 'Asia/Kolkata', utcOffset: 'UTC+05:30' },
  { city: 'Manila', country: 'Philippines', timezone: 'Asia/Manila', utcOffset: 'UTC+08:00' },
  { city: 'Guangzhou', country: 'China', timezone: 'Asia/Shanghai', utcOffset: 'UTC+08:00' },
  { city: 'Lagos', country: 'Nigeria', timezone: 'Africa/Lagos', utcOffset: 'UTC+01:00' },
  { city: 'Rio de Janeiro', country: 'Brazil', timezone: 'America/Sao_Paulo', utcOffset: 'UTC-03:00' },
  { city: 'Shenzhen', country: 'China', timezone: 'Asia/Shanghai', utcOffset: 'UTC+08:00' },
  { city: 'Kinshasa', country: 'DR Congo', timezone: 'Africa/Kinshasa', utcOffset: 'UTC+01:00' },
  { city: 'Tianjin', country: 'China', timezone: 'Asia/Shanghai', utcOffset: 'UTC+08:00' },
  { city: 'London', country: 'United Kingdom', timezone: 'Europe/London', utcOffset: 'UTC+00:00' },
  { city: 'Bangalore', country: 'India', timezone: 'Asia/Kolkata', utcOffset: 'UTC+05:30' },
  { city: 'Chengdu', country: 'China', timezone: 'Asia/Shanghai', utcOffset: 'UTC+08:00' },
  { city: 'Moscow', country: 'Russia', timezone: 'Europe/Moscow', utcOffset: 'UTC+03:00' },
  { city: 'Seoul', country: 'South Korea', timezone: 'Asia/Seoul', utcOffset: 'UTC+09:00' },
  { city: 'Lahore', country: 'Pakistan', timezone: 'Asia/Karachi', utcOffset: 'UTC+05:00' },
  { city: 'Jakarta', country: 'Indonesia', timezone: 'Asia/Jakarta', utcOffset: 'UTC+07:00' },
  { city: 'Lima', country: 'Peru', timezone: 'America/Lima', utcOffset: 'UTC-05:00' },
  { city: 'Paris', country: 'France', timezone: 'Europe/Paris', utcOffset: 'UTC+01:00' },
  { city: 'Berlin', country: 'Germany', timezone: 'Europe/Berlin', utcOffset: 'UTC+01:00' },
  { city: 'Hyderabad', country: 'India', timezone: 'Asia/Kolkata', utcOffset: 'UTC+05:30' },
  { city: 'Nanjing', country: 'China', timezone: 'Asia/Shanghai', utcOffset: 'UTC+08:00' },
  { city: 'Ho Chi Minh City', country: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh', utcOffset: 'UTC+07:00' },
  { city: 'Alexandria', country: 'Egypt', timezone: 'Africa/Cairo', utcOffset: 'UTC+02:00' },
  { city: 'Ahmedabad', country: 'India', timezone: 'Asia/Kolkata', utcOffset: 'UTC+05:30' },
  { city: 'Khartoum', country: 'Sudan', timezone: 'Africa/Khartoum', utcOffset: 'UTC+02:00' },
  { city: 'Singapore', country: 'Singapore', timezone: 'Asia/Singapore', utcOffset: 'UTC+08:00' },
  { city: 'Riyadh', country: 'Saudi Arabia', timezone: 'Asia/Riyadh', utcOffset: 'UTC+03:00' },
  { city: 'Baghdad', country: 'Iraq', timezone: 'Asia/Baghdad', utcOffset: 'UTC+03:00' },
  { city: 'Toronto', country: 'Canada', timezone: 'America/Toronto', utcOffset: 'UTC-05:00' },
  { city: 'Surat', country: 'India', timezone: 'Asia/Kolkata', utcOffset: 'UTC+05:30' },
  { city: 'Madrid', country: 'Spain', timezone: 'Europe/Madrid', utcOffset: 'UTC+01:00' },
  { city: 'Hong Kong', country: 'Hong Kong', timezone: 'Asia/Hong_Kong', utcOffset: 'UTC+08:00' },
  { city: 'Dar es Salaam', country: 'Tanzania', timezone: 'Africa/Dar_es_Salaam', utcOffset: 'UTC+03:00' },
  { city: 'Sydney', country: 'Australia', timezone: 'Australia/Sydney', utcOffset: 'UTC+11:00' },
  { city: 'Melbourne', country: 'Australia', timezone: 'Australia/Melbourne', utcOffset: 'UTC+11:00' },
  { city: 'Nairobi', country: 'Kenya', timezone: 'Africa/Nairobi', utcOffset: 'UTC+03:00' },
  { city: 'Taipei', country: 'Taiwan', timezone: 'Asia/Taipei', utcOffset: 'UTC+08:00' },
  { city: 'Rome', country: 'Italy', timezone: 'Europe/Rome', utcOffset: 'UTC+01:00' },
  { city: 'Bogota', country: 'Colombia', timezone: 'America/Bogota', utcOffset: 'UTC-05:00' },
  { city: 'Bangkok', country: 'Thailand', timezone: 'Asia/Bangkok', utcOffset: 'UTC+07:00' },
  { city: 'Johannesburg', country: 'South Africa', timezone: 'Africa/Johannesburg', utcOffset: 'UTC+02:00' },
  { city: 'Chennai', country: 'India', timezone: 'Asia/Kolkata', utcOffset: 'UTC+05:30' },
  { city: 'Buenos Aires', country: 'Argentina', timezone: 'America/Argentina/Buenos_Aires', utcOffset: 'UTC-03:00' },
  { city: 'Ankara', country: 'Turkey', timezone: 'Europe/Istanbul', utcOffset: 'UTC+03:00' },
  { city: 'Santiago', country: 'Chile', timezone: 'America/Santiago', utcOffset: 'UTC-04:00' },
  { city: 'Kuala Lumpur', country: 'Malaysia', timezone: 'Asia/Kuala_Lumpur', utcOffset: 'UTC+08:00' },
  { city: 'Casablanca', country: 'Morocco', timezone: 'Africa/Casablanca', utcOffset: 'UTC+01:00' },
  { city: 'Vienna', country: 'Austria', timezone: 'Europe/Vienna', utcOffset: 'UTC+01:00' },
  { city: 'Brasilia', country: 'Brazil', timezone: 'America/Sao_Paulo', utcOffset: 'UTC-03:00' },
  { city: 'San Francisco', country: 'United States', timezone: 'America/Los_Angeles', utcOffset: 'UTC-08:00' },
  { city: 'Los Angeles', country: 'United States', timezone: 'America/Los_Angeles', utcOffset: 'UTC-08:00' },
  { city: 'Chicago', country: 'United States', timezone: 'America/Chicago', utcOffset: 'UTC-06:00' },
  { city: 'Miami', country: 'United States', timezone: 'America/New_York', utcOffset: 'UTC-05:00' },
  { city: 'Dallas', country: 'United States', timezone: 'America/Chicago', utcOffset: 'UTC-06:00' },
  { city: 'Houston', country: 'United States', timezone: 'America/Chicago', utcOffset: 'UTC-06:00' },
  { city: 'Toronto', country: 'Canada', timezone: 'America/Toronto', utcOffset: 'UTC-05:00' },
  { city: 'Vancouver', country: 'Canada', timezone: 'America/Vancouver', utcOffset: 'UTC-08:00' },
  { city: 'Montreal', country: 'Canada', timezone: 'America/Toronto', utcOffset: 'UTC-05:00' },
  { city: 'Lisbon', country: 'Portugal', timezone: 'Europe/Lisbon', utcOffset: 'UTC+00:00' },
  { city: 'Dublin', country: 'Ireland', timezone: 'Europe/Dublin', utcOffset: 'UTC+00:00' },
  { city: 'Amsterdam', country: 'Netherlands', timezone: 'Europe/Amsterdam', utcOffset: 'UTC+01:00' },
  { city: 'Brussels', country: 'Belgium', timezone: 'Europe/Brussels', utcOffset: 'UTC+01:00' },
  { city: 'Zurich', country: 'Switzerland', timezone: 'Europe/Zurich', utcOffset: 'UTC+01:00' },
  { city: 'Stockholm', country: 'Sweden', timezone: 'Europe/Stockholm', utcOffset: 'UTC+01:00' },
  { city: 'Oslo', country: 'Norway', timezone: 'Europe/Oslo', utcOffset: 'UTC+01:00' },
  { city: 'Copenhagen', country: 'Denmark', timezone: 'Europe/Copenhagen', utcOffset: 'UTC+01:00' },
  { city: 'Helsinki', country: 'Finland', timezone: 'Europe/Helsinki', utcOffset: 'UTC+02:00' },
  { city: 'Warsaw', country: 'Poland', timezone: 'Europe/Warsaw', utcOffset: 'UTC+01:00' },
  { city: 'Prague', country: 'Czech Republic', timezone: 'Europe/Prague', utcOffset: 'UTC+01:00' },
  { city: 'Budapest', country: 'Hungary', timezone: 'Europe/Budapest', utcOffset: 'UTC+01:00' },
  { city: 'Athens', country: 'Greece', timezone: 'Europe/Athens', utcOffset: 'UTC+02:00' },
  { city: 'Bucharest', country: 'Romania', timezone: 'Europe/Bucharest', utcOffset: 'UTC+02:00' },
  { city: 'Tel Aviv', country: 'Israel', timezone: 'Asia/Jerusalem', utcOffset: 'UTC+02:00' },
  { city: 'Dubai', country: 'UAE', timezone: 'Asia/Dubai', utcOffset: 'UTC+04:00' },
  { city: 'Abu Dhabi', country: 'UAE', timezone: 'Asia/Dubai', utcOffset: 'UTC+04:00' },
  { city: 'Doha', country: 'Qatar', timezone: 'Asia/Qatar', utcOffset: 'UTC+03:00' },
  { city: 'Kuwait City', country: 'Kuwait', timezone: 'Asia/Kuwait', utcOffset: 'UTC+03:00' },
  { city: 'Bahrain', country: 'Bahrain', timezone: 'Asia/Bahrain', utcOffset: 'UTC+03:00' },
  { city: 'Muscat', country: 'Oman', timezone: 'Asia/Muscat', utcOffset: 'UTC+04:00' },
  { city: 'Wellington', country: 'New Zealand', timezone: 'Pacific/Auckland', utcOffset: 'UTC+13:00' },
  { city: 'Auckland', country: 'New Zealand', timezone: 'Pacific/Auckland', utcOffset: 'UTC+13:00' },
  { city: 'Brisbane', country: 'Australia', timezone: 'Australia/Brisbane', utcOffset: 'UTC+10:00' },
  { city: 'Perth', country: 'Australia', timezone: 'Australia/Perth', utcOffset: 'UTC+08:00' },
  { city: 'Adelaide', country: 'Australia', timezone: 'Australia/Adelaide', utcOffset: 'UTC+10:30' },
  { city: 'Cape Town', country: 'South Africa', timezone: 'Africa/Johannesburg', utcOffset: 'UTC+02:00' },
  { city: 'Accra', country: 'Ghana', timezone: 'Africa/Accra', utcOffset: 'UTC+00:00' },
  { city: 'Addis Ababa', country: 'Ethiopia', timezone: 'Africa/Addis_Ababa', utcOffset: 'UTC+03:00' },
  { city: 'Dakar', country: 'Senegal', timezone: 'Africa/Dakar', utcOffset: 'UTC+00:00' },
  { city: 'Havana', country: 'Cuba', timezone: 'America/Havana', utcOffset: 'UTC-05:00' },
  { city: 'Santo Domingo', country: 'Dominican Republic', timezone: 'America/Santo_Domingo', utcOffset: 'UTC-04:00' },
  { city: 'Guatemala City', country: 'Guatemala', timezone: 'America/Guatemala', utcOffset: 'UTC-06:00' },
  { city: 'Helsinki', country: 'Finland', timezone: 'Europe/Helsinki', utcOffset: 'UTC+02:00' },
  { city: 'Tallinn', country: 'Estonia', timezone: 'Europe/Tallinn', utcOffset: 'UTC+02:00' },
  { city: 'Riga', country: 'Latvia', timezone: 'Europe/Riga', utcOffset: 'UTC+02:00' },
  { city: 'Vilnius', country: 'Lithuania', timezone: 'Europe/Vilnius', utcOffset: 'UTC+02:00' },
  { city: 'Reykjavik', country: 'Iceland', timezone: 'Atlantic/Reykjavik', utcOffset: 'UTC+00:00' },
  { city: 'Luxembourg', country: 'Luxembourg', timezone: 'Europe/Luxembourg', utcOffset: 'UTC+01:00' },
]

export function searchCities(query: string): CityData[] {
  if (!query || query.length < 2) return []
  const lower = query.toLowerCase()
  return CITIES.filter(
    (c) => c.city.toLowerCase().includes(lower) || c.country.toLowerCase().includes(lower),
  ).slice(0, 8)
}
